#!/bin/bash

set -o errexit -o nounset -o pipefail

install_deps() {
    python3 -m pip install .
    python3 -m pip install azure-storage-blob azure-identity
}

install_extensions() {
    cd test/extensions
    sh install_packages.sh
    cd ../../
}

run_tests() {
  cd test/core && PYTHONPATH=`pwd`/../../ python3 run_tests.py --inherit-env --num-parallel 8
}

install_deps && install_extensions && env && run_tests
