#!/bin/bash

set -o errexit -o nounset -o pipefail

install_deps() {
    python3 -m pip install .
    python3 -m pip install pytest
    if [ "${METAFLOW_TEST_UNIT_INCLUDE_AZURE:-0}" == "1" ]; then
        python3 -m pip install azure-storage-blob azure-identity
    fi
}

run_unit_tests() {
    cd test/unit
    if [ "${METAFLOW_TEST_UNIT_INCLUDE_AZURE:-0}" == "1" ]; then
        PYTHONPATH=`pwd`/../../ pytest azure
    fi
    PYTHONPATH=`pwd`/../../ pytest standard

}

install_deps && run_unit_tests
